### ISSUE TITLE
Getting error when requesting sdr data

### ISSUE THREAD

**Issue by puneetk11** [imanuelcostigan/dataonderivatives#23]
Hi, 

I am new to R. This is my first use of a package so it is possible I am missing something very basic. 
Note that I am trying to get transaction level data.

1)When I try to get Bloomberg SDR data, I get the following error:
> df1 <- get_bsdr_data(lubridate::ymd(20170109), "CR", 0)
Error: lexical error: invalid char in json text.
                                       request validation fail
                     (right here) ------^

2)When I try to get DTCC SDR data,, I get the following error:
> df1 <- get_ddr_data(lubridate::ymd(20170109), "CR", 0)
Error in return(readr::read_csv(ddrfile[1]), col_types = NULL) : 
  multi-argument returns are not permitted
In addition: Warning message:
`url_ok(x)` is deprecated; please use `identical(status_code(x), 200L)` instead.

Can you please help me understand the issue here? Your help will be greatly appreciated!

Thanks!

**Comment by imanuelcostigan** [comment]
BSDR API has changed. A few things need to be updated:

* The `sorting_column` field needs to be passed to API otherwise fails with either validation or application errors
* Results are now paginated (maybe they were previously paginated but I didn't notice?), so need to work out how to deal with this. The first result returns total number of records which can be used as a counter to loop to.

**Comment by imanuelcostigan** [comment]
Closed in https://github.com/imanuelcostigan/dataonderivatives/commit/04c7f7ba9a38e0f0403b7de4c211b3ff03dedfa2

**Comment by puneetk11** [comment]
Thanks a lot for looking into this. I will try using the updated package.
